#pragma once
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
#include<iostream>
using namespace std;	//НИКОГДА И НЕ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ НЕЛЬЗЯ ПИСАТЬ В ЗАГЛОВОЧНЫХ ФАЙЛАХ